// Object {
//     "album": Object {
//       "album_type": "ALBUM",
//       "artists": Array [
//         Object {
//           "external_urls": Object {
//             "spotify": "https://open.spotify.com/artist/4pejUc4iciQfgdX6OKulQn",
//           },
//           "href": "https://api.spotify.com/v1/artists/4pejUc4iciQfgdX6OKulQn",
//           "id": "4pejUc4iciQfgdX6OKulQn",
//           "name": "Queens of the Stone Age",
//           "type": "artist",
//           "uri": "spotify:artist:4pejUc4iciQfgdX6OKulQn",
//         },
//       ],
//       "available_markets": Array [
//         "CA",
//         "MX",
//         "US",
//       ],
//       "external_urls": Object {
//         "spotify": "https://open.spotify.com/album/58HZZpS0wxJKwGjoerg0mk",
//       },
//       "href": "https://api.spotify.com/v1/albums/58HZZpS0wxJKwGjoerg0mk",
//       "id": "58HZZpS0wxJKwGjoerg0mk",
//       "images": Array [
//         Object {
//           "height": 640,
//           "url": "https://i.scdn.co/image/ab67616d0000b2739b62c36a1f8ac00d60f460cc",
//           "width": 640,
//         },
//         Object {
//           "height": 300,
//           "url": "https://i.scdn.co/image/ab67616d00001e029b62c36a1f8ac00d60f460cc",
//           "width": 300,
//         },
//         Object {
//           "height": 64,
//           "url": "https://i.scdn.co/image/ab67616d000048519b62c36a1f8ac00d60f460cc",
//           "width": 64,
//         },
//       ],
//       "name": "Songs For The Deaf",
//       "release_date": "2002",
//       "release_date_precision": "year",
//       "total_tracks": 15,
//       "type": "album",
//       "uri": "spotify:album:58HZZpS0wxJKwGjoerg0mk",
//     },
//     "artists": Array [
//       Object {
//         "external_urls": Object {
//           "spotify": "https://open.spotify.com/artist/4pejUc4iciQfgdX6OKulQn",
//         },
//         "href": "https://api.spotify.com/v1/artists/4pejUc4iciQfgdX6OKulQn",
//         "id": "4pejUc4iciQfgdX6OKulQn",
//         "name": "Queens of the Stone Age",
//         "type": "artist",
//         "uri": "spotify:artist:4pejUc4iciQfgdX6OKulQn",
//       },
//     ],
//     "available_markets": Array [
//       "CA",
//       "MX",
//       "US",
//     ],
//     "disc_number": 1,
//     "duration_ms": 278706,
//     "explicit": false,
//     "external_ids": Object {
//       "isrc": "USIR10211291",
//     },
//     "external_urls": Object {
//       "spotify": "https://open.spotify.com/track/6NvRxjfYkkT2SpirAlmsjH",
//     },
//     "href": "https://api.spotify.com/v1/tracks/6NvRxjfYkkT2SpirAlmsjH",
//     "id": "6NvRxjfYkkT2SpirAlmsjH",
//     "is_local": false,
//     "name": "No One Knows",
//     "popularity": 66,
//     "preview_url": null,
//     "track_number": 3,
//     "type": "track",
//     "uri": "spotify:track:6NvRxjfYkkT2SpirAlmsjH",
//   }
//   Object {
//     "album": Object {
//       "album_type": "COMPILATION",
//       "artists": Array [
//         Object {
//           "external_urls": Object {
//             "spotify": "https://open.spotify.com/artist/02da1vDJ2hWqfK7aJL6SJm",
//           },
//           "href": "https://api.spotify.com/v1/artists/02da1vDJ2hWqfK7aJL6SJm",
//           "id": "02da1vDJ2hWqfK7aJL6SJm",
//           "name": "Soul Asylum",
//           "type": "artist",
//           "uri": "spotify:artist:02da1vDJ2hWqfK7aJL6SJm",
//         },
//       ],
//       "available_markets": Array [
//         "AD",
//         "AE",
//         "AG",
//         "AL",
//         "AM",
//         "AO",
//         "AR",
//         "AT",
//         "AU",
//         "AZ",
//         "BA",
//         "BB",
//         "BD",
//         "BE",
//         "BF",
//         "BG",
//         "BH",
//         "BI",
//         "BJ",
//         "BN",
//         "BO",
//         "BR",
//         "BS",
//         "BT",
//         "BW",
//         "BY",
//         "BZ",
//         "CA",
//         "CD",
//         "CG",
//         "CH",
//         "CI",
//         "CL",
//         "CM",
//         "CO",
//         "CR",
//         "CV",
//         "CW",
//         "CY",
//         "CZ",
//         "DE",
//         "DJ",
//         "DK",
//         "DM",
//         "DO",
//         "DZ",
//         "EC",
//         "EE",
//         "EG",
//         "ES",
//         "FI",
//         "FJ",
//         "FM",
//         "FR",
//         "GA",
//         "GD",
//         "GE",
//         "GH",
//         "GM",
//         "GN",
//         "GQ",
//         "GR",
//         "GT",
//         "GW",
//         "GY",
//         "HK",
//         "HN",
//         "HR",
//         "HT",
//         "HU",
//         "ID",
//         "IE",
//         "IL",
//         "IN",
//         "IQ",
//         "IS",
//         "IT",
//         "JM",
//         "JO",
//         "JP",
//         "KE",
//         "KG",
//         "KH",
//         "KI",
//         "KM",
//         "KN",
//         "KR",
//         "KW",
//         "KZ",
//         "LA",
//         "LB",
//         "LC",
//         "LI",
//         "LK",
//         "LR",
//         "LS",
//         "LT",
//         "LU",
//         "LV",
//         "LY",
//         "MA",
//         "MC",
//         "MD",
//         "ME",
//         "MG",
//         "MH",
//         "MK",
//         "ML",
//         "MN",
//         "MO",
//         "MR",
//         "MT",
//         "MU",
//         "MV",
//         "MW",
//         "MX",
//         "MY",
//         "MZ",
//         "NA",
//         "NE",
//         "NG",
//         "NI",
//         "NL",
//         "NO",
//         "NP",
//         "NR",
//         "NZ",
//         "OM",
//         "PA",
//         "PE",
//         "PG",
//         "PH",
//         "PK",
//         "PL",
//         "PS",
//         "PT",
//         "PW",
//         "PY",
//         "QA",
//         "RO",
//         "RS",
//         "RW",
//         "SA",
//         "SB",
//         "SC",
//         "SE",
//         "SG",
//         "SI",
//         "SK",
//         "SL",
//         "SM",
//         "SN",
//         "SR",
//         "ST",
//         "SV",
//         "SZ",
//         "TD",
//         "TG",
//         "TH",
//         "TJ",
//         "TL",
//         "TN",
//         "TO",
//         "TR",
//         "TT",
//         "TV",
//         "TW",
//         "TZ",
//         "UA",
//         "UG",
//         "US",
//         "UY",
//         "UZ",
//         "VC",
//         "VE",
//         "VN",
//         "VU",
//         "WS",
//         "XK",
//         "ZA",
//         "ZM",
//         "ZW",
//       ],
//       "external_urls": Object {
//         "spotify": "https://open.spotify.com/album/6RARuzN6pIZZnQKwPeY7xQ",
//       },
//       "href": "https://api.spotify.com/v1/albums/6RARuzN6pIZZnQKwPeY7xQ",
//       "id": "6RARuzN6pIZZnQKwPeY7xQ",
//       "images": Array [
//         Object {
//           "height": 640,
//           "url": "https://i.scdn.co/image/ab67616d0000b273891f7bb20ea06c04793f13dd",
//           "width": 640,
//         },
//         Object {
//           "height": 300,
//           "url": "https://i.scdn.co/image/ab67616d00001e02891f7bb20ea06c04793f13dd",
//           "width": 300,
//         },
//         Object {
//           "height": 64,
//           "url": "https://i.scdn.co/image/ab67616d00004851891f7bb20ea06c04793f13dd",
//           "width": 64,
//         },
//       ],
//       "name": "Black Gold: The Best Of Soul Asylum",
//       "release_date": "1986",
//       "release_date_precision": "year",
//       "total_tracks": 19,
//       "type": "album",
//       "uri": "spotify:album:6RARuzN6pIZZnQKwPeY7xQ",
//     },
//     "artists": Array [
//       Object {
//         "external_urls": Object {
//           "spotify": "https://open.spotify.com/artist/02da1vDJ2hWqfK7aJL6SJm",
//         },
//         "href": "https://api.spotify.com/v1/artists/02da1vDJ2hWqfK7aJL6SJm",
//         "id": "02da1vDJ2hWqfK7aJL6SJm",
//         "name": "Soul Asylum",
//         "type": "artist",
//         "uri": "spotify:artist:02da1vDJ2hWqfK7aJL6SJm",
//       },
//     ],
//     "available_markets": Array [
//       "AD",
//       "AE",
//       "AG",
//       "AL",
//       "AM",
//       "AO",
//       "AR",
//       "AT",
//       "AU",
//       "AZ",
//       "BA",
//       "BB",
//       "BD",
//       "BE",
//       "BF",
//       "BG",
//       "BH",
//       "BI",
//       "BJ",
//       "BN",
//       "BO",
//       "BR",
//       "BS",
//       "BT",
//       "BW",
//       "BY",
//       "BZ",
//       "CA",
//       "CD",
//       "CG",
//       "CH",
//       "CI",
//       "CL",
//       "CM",
//       "CO",
//       "CR",
//       "CV",
//       "CW",
//       "CY",
//       "CZ",
//       "DE",
//       "DJ",
//       "DK",
//       "DM",
//       "DO",
//       "DZ",
//       "EC",
//       "EE",
//       "EG",
//       "ES",
//       "FI",
//       "FJ",
//       "FM",
//       "FR",
//       "GA",
//       "GD",
//       "GE",
//       "GH",
//       "GM",
//       "GN",
//       "GQ",
//       "GR",
//       "GT",
//       "GW",
//       "GY",
//       "HK",
//       "HN",
//       "HR",
//       "HT",
//       "HU",
//       "ID",
//       "IE",
//       "IL",
//       "IN",
//       "IQ",
//       "IS",
//       "IT",
//       "JM",
//       "JO",
//       "JP",
//       "KE",
//       "KG",
//       "KH",
//       "KI",
//       "KM",
//       "KN",
//       "KR",
//       "KW",
//       "KZ",
//       "LA",
//       "LB",
//       "LC",
//       "LI",
//       "LK",
//       "LR",
//       "LS",
//       "LT",
//       "LU",
//       "LV",
//       "LY",
//       "MA",
//       "MC",
//       "MD",
//       "ME",
//       "MG",
//       "MH",
//       "MK",
//       "ML",
//       "MN",
//       "MO",
//       "MR",
//       "MT",
//       "MU",
//       "MV",
//       "MW",
//       "MX",
//       "MY",
//       "MZ",
//       "NA",
//       "NE",
//       "NG",
//       "NI",
//       "NL",
//       "NO",
//       "NP",
//       "NR",
//       "NZ",
//       "OM",
//       "PA",
//       "PE",
//       "PG",
//       "PH",
//       "PK",
//       "PL",
//       "PS",
//       "PT",
//       "PW",
//       "PY",
//       "QA",
//       "RO",
//       "RS",
//       "RW",
//       "SA",
//       "SB",
//       "SC",
//       "SE",
//       "SG",
//       "SI",
//       "SK",
//       "SL",
//       "SM",
//       "SN",
//       "SR",
//       "ST",
//       "SV",
//       "SZ",
//       "TD",
//       "TG",
//       "TH",
//       "TJ",
//       "TL",
//       "TN",
//       "TO",
//       "TR",
//       "TT",
//       "TV",
//       "TW",
//       "TZ",
//       "UA",
//       "UG",
//       "US",
//       "UY",
//       "UZ",
//       "VC",
//       "VE",
//       "VN",
//       "VU",
//       "WS",
//       "XK",
//       "ZA",
//       "ZM",
//       "ZW",
//     ],
//     "disc_number": 1,
//     "duration_ms": 266066,
//     "explicit": false,
//     "external_ids": Object {
//       "isrc": "USSM19200612",
//     },
//     "external_urls": Object {
//       "spotify": "https://open.spotify.com/track/3Ib3SJV8ZXuLvDiDb2w1As",
//     },
//     "href": "https://api.spotify.com/v1/tracks/3Ib3SJV8ZXuLvDiDb2w1As",
//     "id": "3Ib3SJV8ZXuLvDiDb2w1As",
//     "is_local": false,
//     "name": "Runaway Train",
//     "popularity": 56,
//     "preview_url": "https://p.scdn.co/mp3-preview/dd75555aeb11b247c5e8ea38e2a28aca27f05126?cid=3448de32fc284d9d953165c8f73d89c7",
//     "track_number": 8,
//     "type": "track",
//     "uri": "spotify:track:3Ib3SJV8ZXuLvDiDb2w1As",
//   }
  